/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.carrpod.marmalade;

public final class R {
  public static final class color {
    public static final int marmalade_bg=0x7f010000;
    public static final int marmalade_blue=0x7f010001;
    public static final int marmalade_dark=0x7f010002;
    public static final int marmalade_fg=0x7f010003;
    public static final int marmalade_gray=0x7f010004;
    public static final int marmalade_green=0x7f010005;
    public static final int marmalade_orange=0x7f010006;
    public static final int marmalade_red=0x7f010007;
    public static final int marmalade_yellow=0x7f010008;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f020000;
  }
  public static final class string {
    public static final int app_name=0x7f030000;
    public static final int app_subtitle=0x7f030001;
    public static final int app_version=0x7f030002;
    public static final int bluetooth_title=0x7f030003;
    public static final int btn_back=0x7f030004;
    public static final int btn_cancel=0x7f030005;
    public static final int btn_save=0x7f030006;
    public static final int btn_send=0x7f030007;
    public static final int dashboard_title=0x7f030008;
    public static final int director_comms_title=0x7f030009;
    public static final int release_memory=0x7f03000a;
    public static final int session_active=0x7f03000b;
    public static final int session_config_title=0x7f03000c;
    public static final int session_empty=0x7f03000d;
    public static final int session_offline=0x7f03000e;
    public static final int session_stale=0x7f03000f;
    public static final int settings_title=0x7f030010;
  }
}